#pragma once
#include "CoreMinimal.h"

#ifndef AS_CAN_GENERATE_JIT
#define AS_CAN_GENERATE_JIT (PLATFORM_WINDOWS || PLATFORM_LINUX)
#endif

#if WITH_EDITOR
#ifndef AS_ENABLE_EDITOR_JITTED_CODE
#define AS_SKIP_JITTED_CODE
#endif
#endif

#ifndef AS_JIT_VERIFY_PROPERTY_OFFSETS
#define AS_JIT_VERIFY_PROPERTY_OFFSETS (!UE_BUILD_SHIPPING && !UE_BUILD_TEST)
#endif

#ifndef AS_WITH_STATIC_JIT_DIAGNOSTICS
#define AS_WITH_STATIC_JIT_DIAGNOSTICS (!UE_BUILD_SHIPPING)
#endif
