foreach(REQUIRED_VARIABLE
	AS_STANDALONE_BINARY_DIR
	AS_STANDALONE_CONFIGURATION
	PACKAGE_ROOT
	PACKAGE_MANIFEST_SCRIPT
	PACKAGE_ARCHIVE)
	if(NOT DEFINED ${REQUIRED_VARIABLE})
		message(FATAL_ERROR "${REQUIRED_VARIABLE} is required")
	endif()
endforeach()

file(REMOVE_RECURSE "${PACKAGE_ROOT}")
file(REMOVE "${PACKAGE_ARCHIVE}")
execute_process(
	COMMAND
		"${CMAKE_COMMAND}" --install "${AS_STANDALONE_BINARY_DIR}"
		--config "${AS_STANDALONE_CONFIGURATION}"
		--prefix "${PACKAGE_ROOT}"
	RESULT_VARIABLE INSTALL_RESULT)
if(NOT INSTALL_RESULT EQUAL 0)
	message(FATAL_ERROR "standalone package install failed: ${INSTALL_RESULT}")
endif()

execute_process(
	COMMAND
		"${CMAKE_COMMAND}"
		"-DPACKAGE_ROOT=${PACKAGE_ROOT}"
		-P "${PACKAGE_MANIFEST_SCRIPT}"
	RESULT_VARIABLE MANIFEST_RESULT)
if(NOT MANIFEST_RESULT EQUAL 0)
	message(FATAL_ERROR "standalone package manifest failed: ${MANIFEST_RESULT}")
endif()

execute_process(
	COMMAND
		"${CMAKE_COMMAND}" -E tar cf "${PACKAGE_ARCHIVE}"
		--format=zip
		.
	WORKING_DIRECTORY "${PACKAGE_ROOT}"
	RESULT_VARIABLE ARCHIVE_RESULT)
if(NOT ARCHIVE_RESULT EQUAL 0)
	message(FATAL_ERROR "standalone package archive failed: ${ARCHIVE_RESULT}")
endif()
